export const DRIVERS = [
  { pos: 1,  code: 'VRS', name: 'Varsen',     team: 'APX', sectors: [2,2,0], gap: 'LEADER', compound: 'S', wear: 18, laps: 8,  ers: 72, ersMode: 'M' },
  { pos: 2,  code: 'BLK', name: 'Blake',      team: 'VLK', sectors: [1,0,0], gap: '+1.563', compound: 'S', wear: 22, laps: 9,  ers: 64, ersMode: 'O' },
  { pos: 3,  code: 'ROH', name: 'Rohner',     team: 'NRD', sectors: [0,1,0], gap: '+0.101', compound: 'M', wear: 35, laps: 14, ers: 88, ersMode: 'M' },
  { pos: 4,  code: 'KAI', name: 'Kaiser',     team: 'VLK', sectors: [3,0,0], gap: '+0.840', compound: 'S', wear: 24, laps: 9,  ers: 41, ersMode: 'M' },
  { pos: 5,  code: 'VEN', name: 'Vento',      team: 'ORB', sectors: [0,0,2], gap: '+0.151', compound: 'M', wear: 41, laps: 15, ers: 23, ersMode: 'N' },
  { pos: 6,  code: 'UYS', name: 'Uysal',      team: 'APX', sectors: [0,0,0], gap: '+0.792', compound: 'S', wear: 28, laps: 10, ers: 55, ersMode: 'O', isPlayer: true },
  { pos: 7,  code: 'HAM', name: 'Hamer',      team: 'TRN', sectors: [1,1,0], gap: '+0.455', compound: 'M', wear: 46, laps: 16, ers: 78, ersMode: 'M' },
  { pos: 8,  code: 'ANT', name: 'Antoli',     team: 'NRD', sectors: [0,0,1], gap: '+0.708', compound: 'H', wear: 12, laps: 5,  ers: 92, ersMode: 'H' },
  { pos: 9,  code: 'TSU', name: 'Tsunoba',    team: 'KRN', sectors: [0,0,0], gap: '+0.473', compound: 'M', wear: 52, laps: 18, ers: 34, ersMode: 'M' },
  { pos: 10, code: 'HLM', name: 'Holman',     team: 'VRT', sectors: [3,0,0], gap: '+0.440', compound: 'M', wear: 38, laps: 13, ers: 60, ersMode: 'M' },
  { pos: 11, code: 'GAS', name: 'Gaston',     team: 'SLC', sectors: [0,1,0], gap: '+0.355', compound: 'S', wear: 15, laps: 6,  ers: 81, ersMode: 'O' },
  { pos: 12, code: 'NOR', name: 'Norden',     team: 'ORB', sectors: [0,0,3], gap: '+0.455', compound: 'M', wear: 44, laps: 16, ers: 18, ersMode: 'N' },
  { pos: 13, code: 'BEA', name: 'Beaumont',   team: 'KRN', sectors: [0,0,0], gap: '+0.911', compound: 'H', wear: 8,  laps: 3,  ers: 96, ersMode: 'M' },
  { pos: 14, code: 'OCO', name: 'Okonma',     team: 'MRD', sectors: [1,0,0], gap: '+0.203', compound: 'S', wear: 20, laps: 8,  ers: 47, ersMode: 'M' },
  { pos: 15, code: 'PIR', name: 'Piraud',     team: 'ORB', sectors: [0,0,0], gap: '+0.422', compound: 'M', wear: 49, laps: 17, ers: 29, ersMode: 'M' },
  { pos: 16, code: 'COL', name: 'Colton',     team: 'VRT', sectors: [0,3,0], gap: '+0.506', compound: 'M', wear: 43, laps: 15, ers: 66, ersMode: 'O' },
  { pos: 17, code: 'ARO', name: 'Aronov',     team: 'HLX', sectors: [0,0,0], gap: '+0.894', compound: 'H', wear: 6,  laps: 2,  ers: 85, ersMode: 'M' },
  { pos: 18, code: 'STR', name: 'Strand',     team: 'MRD', sectors: [0,0,0], gap: '+0.388', compound: 'S', wear: 31, laps: 11, ers: 52, ersMode: 'M' },
  { pos: 19, code: 'HDA', name: 'Hadari',     team: 'HLX', sectors: [0,1,0], gap: '+0.286', compound: 'M', wear: 55, laps: 19, ers: 12, ersMode: 'N' },
  { pos: 20, code: 'BOR', name: 'Bordeleau',  team: 'SLC', sectors: [0,0,0], gap: '+0.557', compound: 'H', wear: 14, laps: 6,  ers: 74, ersMode: 'M' },
];
